sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"
synolia_maintenance:
    resource: "@SynoliaSyliusMaintenancePlugin/Resources/config/admin_routing.yaml"
    prefix: '/%sylius_admin.path_name%'
